[project]
name = "project-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.6.3",
    "google-genai>=1.21.1",
    "pandas>=2.3.0",
    "yfinance>=0.2.63",
]
